# 总配置
upsolve: # 补题
  expiration: 7 # 以 `比赛结束` 开始计算的补题有效期，单位天

# 各个 OJ 的配置（将会用于实例化 ContestRetriever）

vjudge: # vjudge config
  instances:
    - # instance 1
      enable: true # 是否启用此 instance
      title_prefix: "CUC-ACM-2023秋季学期新生" # 检索用的标题
      div: "div1" # div1 or div2, 没有组别可以为 ""
      sheet_name_remover: "CUC-ACM-2023秋季学期" # 用于去除 sheet name 中的前缀

    # - # instance 2（用于：同时在 Vjudge 上进行 div1 和 div 2 训练的情况）
    #   title: "CUC-ACM-2023秋季学期新生" # 检索用的标题
    #   enable: true # 是否启用 vjudge

nowcoder: # 牛客 config
  instances:
    - # instance 1
      enable: true # 是否启用此 instance
      title_prefix: ""
      div: "div2" # div1 or div2, 没有组别可以为 ""
    -  # instance 2

input:
  attendance_path: "acmana/resources/attendance.csv" # 选课人员名单 csv 文件路径
  questionnaire_path: "acmana/resources/CUCACM积分系统信息收集表（收集结果）-CUCACM积分系统信息收集表（收集结果）.csv" # 问卷 csv 文件路径
  using_nickname_cache: true

coloredlogs:
  level: INFO
  fmt: "%(asctime)s %(name)s[%(process)d] %(levelname)s\n%(message)s"

Logging: # logging 配置
  disable_existing_loggers: false
  formatters:
    verbose:
      format: "[%(asctime)s-%(levelname)s-%(name)s] %(message)s"
      datefmt: "%H:%M:%S" # %Y-%m-%d
  handlers:
    console:
      class: logging.StreamHandler
      formatter: verbose
      level: DEBUG # 命令行的记录器设置阈值

    file_handler:
      class: logging.FileHandler
      formatter: verbose
      level: DEBUG
      filename: ./app.log

    # dingtalk:
    #   class: dingtalk_log_handler.DingTalkHandler
    #   formatter: verbose
    #   level: WARNING  # 钉钉的 记录器设置阈值
    #   secret: ""
    #   webhook: https://oapi.dingtalk.com/robot/send?access_token=
    #   timeout: 2  # http request timeout, default 1 second

  loggers:
    "":
      handlers:
        - console
        # - file_handler
        # - dingtalk
      level: INFO
      # propagate: false
  version: 1
