name: Releases

on:
  push:
    tags:
      - "*"
  schedule:
    # - cron: "0 10 * * 3" # 北京时间 18 点星期三
    # - cron: "0 10 * * 6" # 北京时间 18 点星期六
    - cron: "0 10 * * *"  # 每天 6 点
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run:
          # 安装所需要的依赖
          pip3 install -r requirements.txt

      - name: Run acmana
        env:
          VJUDGE_COOKIE: ${{ secrets.VJUDGE_COOKIE }}
          NOWCODER_COOKIE: ${{ secrets.NOWCODER_COOKIE }}
        run: python -m acmana

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "outputs/*"
          allowUpdates: true
          tag: "v0.0.10"
          body: "## CUC 寒假训练积分"
          # commit: true
          #   bodyFile: "body.md"
          # token: ${{ secrets.YOUR_GITHUB_TOKEN }}
