name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Test txt
        run: |
          echo "test" > test.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "test.txt"
          #   bodyFile: "body.md"
          # token: ${{ secrets.YOUR_GITHUB_TOKEN }}
